services:
  # --- INFRAESTRUCTURA ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    user: "telegraf:986" # SUSTITUYE POR TU ID DE GRUPO DOCKER
    cap_add:
      - NET_RAW
    group_add:
      - "988" # <--- AQUÍ pones el ID que te dio 'getent group vboxsf'
    ports:
      - "4317:4317"
    volumes:
      #- ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro  # <--- (Necesario para métricas de host)
      - ./telegraf/tmp:/tmp:rw   # carpeta donde Telegraf puede escribir temporalmente
      - /media/compartida:/media/compartida:rw
      - /dev:/dev:ro
      - /run/udev:/run/udev:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      # Indicamos a Telegraf dónde buscar los datos del sistema real
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
      - TELEGRAF_CONFIG_DIR=/etc/telegraf/telegraf.d

  # --- MICROSERVICIOS BOUTIQUE ---
  frontend:
    image: gcr.io/google-samples/microservices-demo/frontend:v0.10.1
    container_name: boutique-frontend
    restart: always
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=127.0.0.1:8080  #anyadimos esta linea falsa, se necesita para que arranque el frontend aunque no tengamos relamente un servicio  shopping assitant
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - OTEL_SERVICE_NAME=frontend
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace
    ports:
      - "8081:8080"
    depends_on:
      - productcatalogservice


  productcatalogservice:
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
    container_name: boutique-productcatalog
    restart: always
    environment:
      - PORT=3550
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317

  cartservice:
    image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.1
    container_name: boutique-cart
    restart: always
    environment:
      - PORT=7070
      - REDIS_ADDR=redis-cart:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace
    depends_on:
      - redis-cart

  redis-cart:
    image: redis:alpine
    container_name: boutique-redis
    restart: always

  currencyservice:
    image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.1
    container_name: boutique-currency
    restart: always
    environment:
      - PORT=7000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      # Añadimos esto para que el Profiler de Google no proteste
      - PROJECT_ID=tfm-local        
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  shippingservice:
    image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.1
    container_name: boutique-shipping
    restart: always
    environment:
      - PORT=50051
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  paymentservice:
    image: gcr.io/google-samples/microservices-demo/paymentservice:v0.10.1
    container_name: boutique-payment
    restart: always
    environment:
      - PORT=50051
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  emailservice:
    image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
    container_name: boutique-email
    restart: always
    environment:
      - PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317

      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  checkoutservice:
    image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.1
    container_name: boutique-checkout
    restart: always
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  recommendationservice:
    image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.1
    container_name: boutique-recommendation
    restart: always
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  adservice:
    image: gcr.io/google-samples/microservices-demo/adservice:v0.10.1
    container_name: boutique-ad
    restart: always
    environment:
      - PORT=9555
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
      - PROJECT_ID=tfm-local
      - DISABLE_PROFILER=1
      - DISABLE_TRACING=1  # Esto evita que intenten conectar con Google Trace

  loadgenerator:
    image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.1
    container_name: boutique-loadgenerator
    restart: always
    environment:
      - FRONTEND_ADDR=frontend:8080
      - USERS=10
    depends_on:
      - frontend

volumes:
  portainer_data:
