[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "1s"
  hostname = "TFM-MICROSERVICIOS-SERV"
  omit_hostname = false



# ---------------------------------------------------------
# --- SALIDAS ---
# ---------------------------------------------------------

#[[outputs.file]]
  #files = ["stdout"]
# ---------------------------------------------------------
# SALIDA TEMPORAL A ARCHIVO (Para verificar que funciona)
# ---------------------------------------------------------
[[outputs.file]]
  files = ["/tmp/telegraf_host_metrics.out"]
  data_format = "json"
  rotation_interval = "24h"
  rotation_max_size = "10MB"
  rotation_max_archives = 10 

  [outputs.file.tagdrop]
    destino = ["archivo_ping"] # <--- "Si ves esta etiqueta, no lo escribas aquí"

[[outputs.file]]
  files = ["/tmp/ping_metrics.out"]
  data_format = "json" # O "influx" para texto plano
  
  tagexclude = ["destino","protocol","port"]
  # FILTRO  Solo acepta métricas que tengan este tag
  [outputs.file.tagpass]
    destino = ["archivo_ping"]




#[[outputs.file]]
  #files = ["/media/compartida/telegraf_host_metrics.out"]
  #data_format = "json"


