[[inputs.docker]]
  ## Dirección del socket de docker
  endpoint = "unix:///var/run/docker.sock"
  #tagexclude = [
    #"com.docker.compose.config-hash", 
    #"com.docker.compose.container-number",
    #"com.docker.compose.depends_on",
    #"com.docker.compose.image",
    #"com.docker.compose.oneoff",
    #"com.docker.compose.project",
    #"com.docker.compose.project.config_files",
    #"com.docker.compose.project.working_dir",
    #"com.docker.compose.version",
    #"container_image",
    #"container_version",
    #"engine_host",
    #"server_version",
    #"com.docker.desktop.extension.icon",
    #"com.docker.extension.detailed-description"
  #]
  fielddrop = ["container_id"]
  taginclude = [
    "container_status",
    "host", 
    "container_name"
  ] 
  ### Si quieres ver la CPU por cada núcleo del contenedor
  #perdevice = false 
  #
  ### Si quieres ver el uso total de CPU del contenedor memoria y CPU
  #total = true
#
  ### Solo monitorizar contenedores que estén corriendo
  #container_status_include = ["running", "exited", "created", "paused"]
#
  ### IMPORTANTE: Esto añade el nombre del contenedor a las métricas
  #container_name_include = []
  #container_names = []

