[[inputs.net]]
  ## Define las interfaces que quieres monitorizar (ej: ["eth0", "enp0s3"])
  ## Si lo dejas vacío, monitoriza todas.
  interfaces = ['eth0']



[[inputs.ping]]
  fieldpass = ["average_response_ms", "percent_packet_loss"]
  ## Lista completa de microservicios de la Online Boutique
  urls = [
    "frontend",
    "adservice",
    "cartservice",
    "checkoutservice",
    "currencyservice",
    "emailservice",
    "paymentservice",
    "productcatalogservice",
    "recommendationservice",
    "shippingservice",
    "redis-cart"
  ]
  
  ## Método nativo para evitar problemas de permisos de root en Docker
  #method = "native"
  method = "exec"
  
  ## Configuración de ejecución
  count = 2           # Con 2 paquetes es suficiente para detectar latencia sin saturar
  ping_interval = 1.0 # Pausa entre paquetes
  timeout = 2.0       # Tiempo máximo de espera por respuesta

  [inputs.ping.tags]
    destino = "archivo_ping"


# FRONTEND
[[inputs.net_response]]
  address = "frontend:8080"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "frontend"

# AD SERVICE
[[inputs.net_response]]
  address = "adservice:9555"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "adservice"

# CART SERVICE
[[inputs.net_response]]
  address = "cartservice:7070"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "cartservice"


# PRODUCT CATALOG
[[inputs.net_response]]
  address = "productcatalogservice:3550"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "productcatalog"

# REDIS CART
[[inputs.net_response]]
  address = "redis-cart:6379"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "redis-cart"

# currencyservice
[[inputs.net_response]]
  address = "currencyservice:7000"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "currencyservice"


# currencyservice
[[inputs.net_response]]
  address = "shippingservice:50051"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "shippingservice"



# paymentservice
[[inputs.net_response]]
  address = "paymentservice:50051"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "paymentservice"


# emailservice
[[inputs.net_response]]
  address = "paymentservice:8080"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "emailservice"


# checkoutservice
[[inputs.net_response]]
  address = "checkoutservice:5050"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "checkoutservice"

# recommendationservice
[[inputs.net_response]]
  address = "recommendationservice:8080"
  protocol = "tcp"
  read_timeout = "2s"
  fieldpass = ["response_time"]
  [inputs.net_response.tags]
    destino = "archivo_ping"
    service_name = "recommendationservice"

