[[inputs.cpu]]
  ## Si es true, recoge datos de cada núcleo por separado
  percpu = true
  ## Si es true, recoge el total global
  totalcpu = true
  ## No necesitamos el tiempo de CPU detallado para el TFM, así ahorramos espacio
  collect_cpu_time = false
  ## Reporta el uso activo en porcentaje
  report_active = true

[[inputs.mem]]
  # Recogerá: total, disponible, usada, libre, buffered y cached

[[inputs.disk]]
  ## Ignorar sistemas de archivos virtuales de Linux que no nos interesan
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "autofs", "zfs"]

[[inputs.diskio]]
  ## Por defecto recoge todos los discos (sda, sdb, etc.)
  ## Es vital para detectar si la base de datos Postgres está saturando el disco físico


