version: '3.8'

services:
  postgres_db:
    image: timescale/timescaledb:latest-pg16
    container_name: ${TIMESCALE_CONTAINER_NAME}}
    restart: always
    # Le decimos a este servicio que busque el .env un nivel arriba (en la raíz)
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASS_DB}
      - POSTGRES_DB=${NAME_DB}
    ports:
      - "${DB_PORT_EXPOSED}:5432"
    volumes:
      - "${PATH_VOLUMEN}:/var/lib/postgresql/data"